### ISSUE TITLE
vulnerabilities in demo

### ISSUE THREAD

**Issue by FDiskas** [ablestack/graphql-codegen-hasura#25]
In a example "demo" folder project has allot outdated dependencies
```
found 10544 vulnerabilities (10537 low, 7 high)
```
To fix this run
```
npm audit fix --force
```

**Comment by FDiskas** [comment]
But I still can't run tests - got error about dependency issues

**Comment by jamshally** [comment]
The dependencies have been updated

**Comment by FDiskas** [comment]
cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
